// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int32
	Name      pgtype.Text
	Data      []byte
	CreatedAt pgtype.Timestamptz
	StationID int32
}

type IrcChannel struct {
	ID        int32
	StationID int32
	CreatedAt pgtype.Timestamptz
	Server    string
	Channel   string
}

type Message struct {
	ID        int32
	StationID int32
	Body      pgtype.Text
	Nick      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Play struct {
	ID        int32
	TrackID   int32
	CreatedAt pgtype.Timestamptz
	Action    string
}

type RecentlyAdded struct {
	ID       int32
	Filename string
	AddedAt  pgtype.Timestamptz
	EventID  int32
	Name     pgtype.Text
	Data     []byte
}

type RecentlyPlayed struct {
	ID        int32
	TrackID   int32
	CreatedAt pgtype.Timestamptz
	PlayedAt  pgtype.Timestamptz
	Filename  string
	EventID   int32
	Action    string
}

type Result struct {
	ID        int32
	Name      pgtype.Text
	Data      []byte
	EventID   int32
	StationID int32
}

type Skip struct {
	ID      int32
	TrackID int32
	Ts      pgtype.Timestamptz
}

type Station struct {
	ID        int32
	Slug      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Track struct {
	ID        int32
	Filename  string
	CreatedAt pgtype.Timestamptz
	Bucket    int32
	Fuzz      float32
	EventID   int32
	StationID int32
	Metadata  []byte
}

type TrackChange struct {
	ID        int32
	TrackID   int32
	CreatedAt pgtype.Timestamptz
}

type TrackEvent struct {
	ID        int32
	TrackID   int32
	CreatedAt pgtype.Timestamptz
	Action    string
	StationID int32
}
