name: deploy

concurrency: production

on:
  push:
    branches:
      - main
    tags:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Create secrets file
        run: echo "${{ secrets.COOKIES }}" > ./gap/vbin/cookies.txt
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u rcy0 --password-stdin
      - name: docker-build
        run: make -C gap docker-build
      - name: docker-push
        run: make -C gap docker-push
      - name: deploy
        run: |
          curl -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" "http://5.78.65.218:8000/api/v1/deploy?uuid=gcgks4skk44ow8400w0sgk84" | tee /dev/stderr | grep -q queued
